name: Run the private Nextflu builds

on:
  workflow_dispatch:
    inputs:
      dockerImage:
        description: "Specific container image to use for build (will override the default of `nextstrain build`)"
        required: false
        type: string

jobs:
  run-build:
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      runtime: aws-batch
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: ${{ inputs.dockerImage }}
      run: |
        nextstrain build \
          --detach \
          --cpus 36 \
          --memory 72gib \
          . \
          all_who \
          -p \
          --configfile profiles/private.nextflu.org.yaml

  deploy-private-nextflu:
    needs: [run-build]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy-private-nextflu
        run: |
          gh workflow run \
            deploy-private-nextflu.yaml \
            --repo nextstrain/seasonal-flu \
            -f aws_batch_job_id=${{ needs.run-build.outputs.aws-batch-job-id }} \
            -f deploy_to_staging=false
        env:
          GITHUB_TOKEN: ${{ github.token }}
