name: Run Nextclade on all sequences

on:
  workflow_dispatch:
    inputs:
      dockerImage:
        description: "Specific container image to use for build (will override the default of `nextstrain build`)"
        required: false
        type: string
      nextcladeServer:
        description: "URL for a Nextclade server from which Nextclade datasets should be downloaded instead of the default public server"
        required: false
        type: string
  workflow_call:
    inputs:
      artifact-name:
        description: "Name to use for final artifact uploaded by this action"
        required: false
        type: string

jobs:
  run-build:
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      artifact-name: ${{ inputs.artifact-name }}
      runtime: aws-batch
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: ${{ inputs.dockerImage }}
      run: |
        nextstrain build \
          --detach \
          --cpus 36 \
          --memory 72gib \
          . \
          upload_all_nextclade_files \
          -p \
          --configfile profiles/nextclade.yaml \
          --config nextclade_server="${{ inputs.nextcladeServer }}" \
          --set-threads run_nextclade=12
